# This file consists of two parts:
# 1. The first part defines the Persistent Volume(pv). Customize the amount of allocated storage in spec.capacity.storage and In spec.hostPath specify the volume mount point.
# 2. The second part of the file defines the Persitent Volume Claim(pvc)

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:                         
  storageClassName: manual   
  capacity:                  
    storage: 10Gi             
  accessModes:                
    - ReadWriteOnce           # This access mode allows the volume to be mounted as read-write by a single node at a time.
  hostPath:                  
    path: "/mnt/data"         # The PV is created using storage located on the host machine at the path “/mnt/data.
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi          # Should be equal or less than the PV capacity created.