# This file consists of two parts:
# 1. The first part defines the Persistent Volume. Customize the amount of allocated storage in spec.capacity.storage. 
# In spec.hostPath specify the volume mount point.
# 2. The second part of the file defines the PVC.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:                         # This section contains the specifications for the PV.
  storageClassName: manual    # Storage class to be used for this PV. A storage class is a way to define the storage provisioner and reclaim policy for the volume.
  capacity:                   # It specifies the storage capacity of the PV.
    storage: 10Gi             # This sets the capacity of the PV to 10gigabytes.
  accessModes:                # This specifies the access modes for the PV.
    - ReadWriteOnce           # This access mode allows the volume to be mounted as read-write by a single node at a time.
  hostPath:                   # This section defines the source of the storage.
    path: "/mnt/data"         # The PV is created using storage located on the host machine at the path “/mnt/data.
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi          # Should be equal or less than the PV capacity created.